core/urls.py
app_name = "core"
from django.urls import path
from . import views

urlpatterns = [
    path("",views.index,name = "home"),
    path("add",views.add,name = "addcollage"),
    path("forms/<slug>",views.forms,name = "forms"),
    path("register/",views.register,name = "register"),
    path("login/",views.user_login,name = "login"),
    path('logout/',views.user_logout,name = 'logout'),
    path('viewstudents/',views.viewStudents,name = 'viewStudents'),
    path('detailview/<int:pk>',views.detailview,name = 'detailview'),
    path('delete/<int:pk>',views.deletecollage,name = 'delete'),
    path('searchdata/',views.searchdata,name = 'searchdata'),
    path('searchcollage/',views.searchcollage,name = 'searchcollage'),
    path('students/colllage/<slug>',views.student,name = "student"),
    path('first-time-login/changepassword',views.change,name = "change")
    ,path('changepassword',views.changepassword,name = "changepassword"),
    path('updateuser/<pk>',views.updateuser,name = "updateuser"),
    path('deleteuser/<pk>',views.deleteuser,name = "deleteuser"),
    path('viewuser',views.viewuser,name = "viewuser"),
    
    
]

qr/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('core.urls')),
    
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
from django.contrib.auth.models import User
import qrcode
from io import BytesIO
from django.core.files import File
from django.template.defaultfilters import slugify
import uuid
from django.conf import settings


class Collage(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    id = models.IntegerField(primary_key = True)
    name = models.CharField(max_length=200)
    address = models.CharField(max_length=500,default=' ')
    image = models.ImageField(upload_to='img',default= ' ')
    # qr_code = models.ImageField(upload_to='qr_codes',blank= True)
    qr_code = models.ImageField(upload_to='qr_codes',blank= True)
    slug = models.SlugField(max_length=200,default = ' ')



    def __str__(self):
        return self.name
    def save(self,*args, **kwargs):
        self.slug = f"{slugify(self.name)}-{str(uuid.uuid4())}"
        site = f"{settings.SITE_URL}forms/{self.slug}"
        

        qr = qrcode.QRCode(version=1,error_correction=qrcode.constants.ERROR_CORRECT_H,box_size=10,border=4)
        qr.add_data(site)
        qr.make(fit=True)
        img = qr.make_image(fill_color ="black",back_color = "white")
        fname = f'qr_code-{self.name}+.png'
        buffer = BytesIO()
        img.save(buffer,'PNG')
        self.qr_code.save(fname,File(buffer),save=False)
        super().save(*args, **kwargs)   

class CollageForm(models.Model):
    collage = models.ForeignKey(Collage,on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    phone = models.CharField(max_length= 200)
    address = models.CharField(max_length=500)
    gpa = models.CharField(max_length=50)  
    faculty = models.CharField(max_length=300)
    is_verified = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.name}-{self.collage}"

core/forms.py
from django import forms
from django.forms import ModelForm
from .models import * 
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.models import User

class StudentForms(ModelForm):
    class Meta: 
        model = CollageForm
        exclude = ('collage',)
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'phone': forms.NumberInput(attrs={'class': 'form-control'}),
            'address': forms.TextInput(attrs={'class': 'form-control'}),
            'gpa': forms.NumberInput(attrs={'class': 'form-control'}),
            'faculty': forms.TextInput(attrs={'class': 'form-control'}),
        }

class PasswordChangingForm(PasswordChangeForm):
    old_password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Old Password'}))
    new_password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'New Passowrd'}))
    new_password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Confirm new password'}))
    class Meta:
        model = User
        fields = ['old_password', 'new_password1', 'new_password2']



# class UserForm(ModelForm):
#     class Meta: 
#         model = User
#         exclude = ('username',)
#         widgets = {
#             'name': forms.TextInput(attrs={'class': 'form-control'}),
#             'email': forms.EmailInput(attrs={'class': 'form-control'}),
            
#         }

core/views.py
from django.shortcuts import render,redirect
from core.models import *
from django.contrib import messages
from django.contrib.auth import authenticate, login,logout,update_session_auth_hash
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from .forms import StudentForms
from django.core.paginator import Paginator
from django.http import JsonResponse
from .forms import PasswordChangingForm
from django.template.loader import render_to_string
# from .forms import CollageForm
@login_required(login_url = 'core:login')
def deletecollage(request,pk):
    if request.user.is_superuser:
        collage = Collage.objects.get(id = pk)
        collage.delete()
        return redirect('core:home')
    return render(request,'core/index.html')
@login_required(login_url = 'core:login')
def student(request,slug):
    if request.user.is_superuser:
        collage = Collage.objects.get(slug = slug)
        students = CollageForm.objects.filter(collage = collage)
        page = request.GET.get('page')
        paginator = Paginator(students,2)
        try:
            students = paginator.page(page)
        except Exception as  PageNotAnInteger:
            students = paginator.page(1)

        except Exception as  EmptyPage:
            collageform = paginator.page(paginator.num_pages)
        return render(request,'core/registeredStudent.html',{'students':students,"page":page})
    return redirect('core:home')
    
@login_required(login_url = 'core:login')
def index(request):
    print(request.user.last_login)
    print(request.user.date_joined)
    # if request.user.last_login == request.user.date_joined:
    #     print(True)
    # else:
    #     print(False)

    # page_obj = None

    if request.user.is_superuser:
        collage = Collage.objects.all()
        p = Paginator(collage, 6)
        page_number = request.GET.get("page",1)
        page_obj = p.get_page(page_number)
        if request.htmx:
            return render(request, 'core/partial/list.html', {'data':page_obj})
    else:
        
        x= Collage.objects.filter(user = request.user).first()
        if x:
            page_obj = Collage.objects.get(user = request.user)
        else:
            page_obj = None
    # print(collage)
    
    return render(request,'core/index.html',{'data':page_obj})
    
def viewStudents(request):
    collage= Collage.objects.filter(user = request.user).first()
    collageform = None
    if collage:
        collageform = CollageForm.objects.filter(collage = collage)
        verification = request.GET.get('status')
        status = 0
        if verification == "verified":
            collageform = CollageForm.objects.filter(collage = collage,is_verified = True)
            
        elif verification == "Not_verified":
            collageform = CollageForm.objects.filter(collage = collage,is_verified = False)
        
        if verification == "verified":
            status = 1
        elif verification == "Not_verified":
            status = 2
        page = request.GET.get('page')
        paginator = Paginator(collageform,10)
        try:
            collageform = paginator.page(page)
        except Exception as  PageNotAnInteger:
            collageform = paginator.page(1)

        except Exception as  EmptyPage:
            collageform = paginator.page(paginator.num_pages)
        

        
    
        return render(request,'core/viewStudents.html',{"students":collageform,'status':status,"page":page})
    return render(request,'core/viewStudents.html',{"students":collageform,})
def register(request):
    if request.user.is_superuser:
        if request.method == "POST":
            username = request.POST.get('username')
            email = request.POST.get('email')
            password = request.POST.get('password')
            cpassword = request.POST.get('confirmpassword')
            print(username,email,password,cpassword)
            context =  {
                "username":username,
                "email":email,


            }
            if User.objects.filter(username = username).first():
                messages.success(request,'Username is taken')
                return redirect('/register')
            if User.objects.filter(email = email).first():
                messages.success(request,'Email is taken')
                return redirect('/register')
            if cpassword!=password:
                messages.success(request,"Passwords didn't match!! Please enter same password")
                return redirect('/register')
            
            user_obj = User.objects.create_user(username = username,email = email,password=password)
            user_obj.save()
        
            return redirect('core:home')
        else:
            return render(request,'core/register.html')
    else:
        return redirect('core:login')
        
        

    
def user_login(request):
    if  not request.user.is_authenticated:
        
        if request.method =='POST':
            username = request.POST.get('username')
            password = request.POST.get('password')
            user = User.objects.get(username = username)
            
           
            # print(username,password)
            user_obj = User.objects.filter(username = username).first()
            if  user_obj is None:
                messages.success(request,'User not found!!! please signin with correct username')
                return redirect('/login')
           
            user = authenticate(username = username,password= password)
            if user is not None:
                if user.last_login:
                    login(request,user)
                    # print(False)
                    return redirect('core:home')
                else:
                    login(request,user)
                    print(True)
                    return redirect('core:change')
            else:
                messages.success(request,'Wrong password')
                return redirect('/login')
            # return redirect('core:home')
            

        return render(request,'core/login.html')
    else:
        return redirect('/')
    
def user_logout(request):
     logout(request)
     return redirect('/login/')
    

def add(request):
    if request.user.is_superuser:
        user = User.objects.all()
        if request.method == 'POST':
            name = request.POST.get('collage')
            address = request.POST.get('address')
            image = request.FILES.get('image')
            username = request.POST.get('username')
            
            if image == None:
                messages.success(request,'Please fill image field') 
                return redirect('/add')
                

            collage = Collage.objects.filter(name = name).first()
            if name == "":
                messages.success(request,'Enter the name of the collage!!!')
            else:
                if collage:
                    messages.success(request,'Collage Already exists')
                else: 
                    x = Collage.objects.create(user = User.objects.get(username = username),name = name,address = address,image = image)
                    collage= Collage.objects.filter(user = request.user).first()
        

                
        return render(request,'core/addCollage.html',{'user':user})
    else:
        return redirect("core:home")

def forms(request,slug):
    
    if request.method == "POST":
        name = request.POST.get('Name')
        phone = request.POST.get('phone')
        address = request.POST.get('address')
        gpa = request.POST.get('gpa')
        faculty= request.POST.get('faculty')
        CollageForm.objects.create(collage = Collage.objects.get(slug = slug),name = name,phone = phone,address = address,gpa = gpa,faculty = faculty)
        


    return render(request,'core/forms.html',{"collage":Collage.objects.filter(slug = slug).first()})




def detailview(request,pk):
    student = CollageForm.objects.get(id = pk)

    form = StudentForms(instance=student)
    if request.method == "POST":
        form = StudentForms(request.POST,instance = student)
        if form.is_valid():
            form.save()
            return redirect('core:viewStudents')
    context = {'form':form}
    return render(request,'core/studentDetail.html',context)

def searchdata(request):
    
    if request.method == "POST":
        
        collage= Collage.objects.filter(user = request.user).first()
        data = request.POST.get('livesearch')
        students = CollageForm.objects.filter(collage = collage, name__icontains = data)
        print(students)
        t = render_to_string('core/partial/search-list.html',{'students':students})

        
        
        return JsonResponse({'data':t})
    return JsonResponse({})

@login_required(login_url = 'core:login')
def change(request):
    # user = User.objects.get(username = request.user.username)
    
    fm = PasswordChangingForm(user = request.user)
    if request.method == 'POST':
        fm = PasswordChangingForm(user = request.user,data = request.POST)
        print(request.POST)
        if fm.is_valid():
            fm.save()
            update_session_auth_hash(request,fm.user)
            messages.success(request,"Password changed successfully")
            return redirect("core:change")
    

    
    return render(request,'core/change.html',{"form":fm})

def searchcollage(request):
    
    if request.method == "POST":
        
        # collage= Collage.objects.filter(name__icontains = data)
        data = request.POST.get('livesearch')
        collage= Collage.objects.filter(name__icontains = data)
        
        print(collage)
        t = render_to_string('core/partial/collage-list.html',{'data':collage})

        
        
        return JsonResponse({'data':t})
    return JsonResponse({})
@login_required(login_url="core:login")
def changepassword(request):

core/templates/core/addCollage.html
{%extends 'base.html'%}
{%load static%}
{%block content%}
<div class="container">
    

    <div class="row justify-content-center my-3 ">
        <div class="col-sm-5 border p-5 shadow  rounded">
            {% if messages %}
                {% for msg in messages %}
                <div class="alert alert-warning alert-dismissible my-3  " role="alert">
                    <button type="button" class="close w-25" data-dismiss="alert" aria-label="Close">x</button>
                    

                    {{msg.message}}
                </div>
                {% endfor %}
            {% endif %}
            <h1 class="mt-5 text-center color-red">Add Collage</h1>
            <hr>    
            <form method = "post" enctype="multipart/form-data">
                {%csrf_token%}
                <div class="form-group">
                    <label for="exampleFormControlSelect1">Select Collage Username</label>
                    <select class="form-control" name = "username">
                    {%for u in user%}
                      <option>{{u.username}}</option>
                    {%endfor%}
                    </select>
                  </div>
                <div class="form-group">
                  <label for="exampleInputEmail1">Collage Name</label>
                  <input type="text" class="form-control" name = "collage">
                </div>
                <div class="form-group">
                    <label for="exampleInputEmail1">Address</label>
                    <input type="text" class="form-control" name = "address">
                </div>
                <div class="form-group">
                    <label>Collage Picture</label>
                    <input class="form-control "  type="file" name = "image" onchange="getimage(event)">
                    
                </div>
                  <div id = "photodiv">
                    <img     id = "newimage" class = "img-thumbnail">
                  </div>

                    
                <div class="row  justify-content-center mt-5">
                    <button type="submit" class="btn btn-primary col-3 rounded  ">Submit</button>
                </div>
                
              </form>
        </div>
    </div>
</div>

<script>
    function getimage(event){
        var image = URL.createObjectURL(event.target.files[0])
        var imagediv = document.getElementById('photodiv')
        var newimage = document.getElementById('newimage')
        newimage.src = image
        imagediv.append
    }
</script>

{%endblock content%}

core/templates/core/collageuserlist.html
{%extends 'base.html'%}

{%block content%}
{%load myapp_extras%}
<style>
  .x{
      background-color: rgb(242, 236, 236);
      
  }
</style>

<div class="container my-5">
  
  <!-- {{status}} -->
    <ul class="nav nav-pills nav-fill border mb-3">

      {%if users%}
    <table class="table border-bottom ">  
        <thead class="">
          <tr>
          
            <th>Users</th>
            <th></th>
            <th></th>
          </tr>
        </thead>
        <tbody id = "tbody">
         {%for user in users%}
            <tr>
              {%if user.username != "admin"%}
                <td>
                    {{user.username}}
                </td>
                <td> <a href="{%url 'core:updateuser' user.id%}" class="btn btn-primary">update</a></td>
                <td> <a href="{%url 'core:deleteuser' user.id%}" class="btn btn-danger">delete</a></td>
                {%endif%}
                
            </tr>
          {%endfor%}

        </tbody>
      </table>
      <!-- {{page}} -->
      <div class="container mt-2">
        <div class="row ">
            <div class="col-md-4 offset-lg-5">
                {%if users.has_other_pages%}
                <div>
                    <ul class="pagination pagination-lg container ">
                        {% if users.has_previous %}
                        <li class="page-item ">
                            <a class="page-link"
                                href="{%my_url users.previous_page_number 'page' request.GET.urlencode %}" tabindex="-1"
                                style="color: black;">Previous</a>
                        </li>
                        {%endif%}
                        {%for i in users.paginator.page_range%}
                        <!-- {{i}} -->
                        <li class="page-item  "><a class="page-link {%if i == page %} x {%endif%}" href="{%my_url i 'page' request.GET.urlencode %}"
                                style="color:rgb(56, 54, 51)">{{i}} </a></li>
      
                        {%endfor%}
                        {% if users.has_next %}
                        <li class="page-item ">
                            <a class="page-link" href="{%my_url users.next_page_number 'page' request.GET.urlencode %}"
                                tabindex="-1" style="color: black;">Next</a>
                        </li>
                        {%endif%}
                    </ul>
                </div>
                {%endif%}
            </div>
        </div>
        </div>
      
     
      
      {%endif%}
  </div>
<script>
   $("#livesearch").keyup(function(){
      var livesearch = $(this).val();
      console.log(livesearch)
      if (livesearch != " "){
        $.ajax(
          {
            type:'POST',
            url:"/searchdata/",
            data:{ 
              'livesearch':livesearch,
              'csrfmiddlewaretoken':'{{ csrf_token }}'
            },
            success:function(res){
              // console.log(data)
              $("#tbody").html(res.data)
            }
          }
        );
      }

   })
</script>
<!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script> -->
{%endblock content%}



1fa

core/templates/core/index.html
{%extends 'base.html'%}

{%block content%}
<div class="container my-5">
  {%if request.user.is_superuser%}
  <form action="" class="mb-2 ml-auto">
    <div class="formgroup">

      <input type="text" class="form-control" placeholder = "search here" name = "livesearch" id = "livesearch">
    </div>
  </form>
  {%endif%}
  {%if data%}
    <table class="table table-sm border">
        <thead>
          <tr>
            <th>Collage</th>
            <th>QR</th>
            <th>Action</th>
          </tr>
        </thead>
        
        <tbody id = 'tbody'>
          
          {%if request.user.is_superuser%}
            {% for d in data%}
          <tr>
            <td class="pt-4 pl-sm-4"><a href="{%url 'core:student' d.slug%}" class="mt-5">{{d.name}}</a></td>
            <td><a href="{{d.qr_code.url}}"><img src="{{d.qr_code.url}}" style = "width: 150px"  alt=""></a></td>
            <td>
              <a href="{%url 'core:delete' d.id%}" class="btn btn-danger  mt-2">Delete</a>
              
              <hr>
              <a href="{{d.qr_code.url}}" class="btn btn-warning  mb-2 mr-3" download> download</a>
              
            </td>
            
          </tr>
          
          {%endfor%}
          {% if data.has_next %}
            <tr id="load-more">
                <td colspan="3" class="text-center">
                    <button class="btn btn-primary"
                            hx-get="{% url 'core:home' %}?page={{data.next_page_number}}"
                            hx-target="#load-more"
                            hx-swap="outerHTML">Load More</button>
                </td>
            </tr>
          {% endif %}
          
          {%else%}
          
          <tr>
            <td><a href="{%url 'core:forms' data.slug%}">{{data.name}}</a></td>
            <td><a href="{{data.qr_code.url}}"><img src="{{data.qr_code.url}}" style = "width: 200px"  alt=""></a></td>
            <td><a href="{{data.qr_code.url}}" class="btn btn-warning" download> download</a></td>
          </tr>
          
          {%endif%}
          
          

  
        </tbody>
      </table>
      {%else%}
      <div class="alert alert-dark" role="alert">
        Collage not registered
      </div>
      {%endif%}
  </div>
  <script>
    $("#livesearch").keyup(function(){
       var livesearch = $(this).val();
       console.log(livesearch)
       if (livesearch != " "){
         $.ajax(
           {
             type:'POST',
             url:"/searchcollage/",
             data:{ 
               'livesearch':livesearch,
               'csrfmiddlewaretoken':'{{ csrf_token }}'
             },
             success:function(res){
               // console.log(data)
               $("#tbody").html(res.data)
             }
           }
         );
       }
 
    })
 </script>
{%endblock content%}

core/templates/core/registeredStudent.html
{%extends 'base.html'%}

{%block content%}
{%load myapp_extras%}
<style>
  .x{
      background-color: rgb(242, 236, 236);
      
  }
</style>

<div class="container my-5">

  <!-- {{status}} -->

      {%if students%}
    <table class="table border-bottom ">  
        <thead class="">
          <tr>
          
            <th>Students</th>
            <th></th>
          </tr>
        </thead>
        <tbody id = "tbody">
         {%for student in students%}
            <tr>
              
                <td>
                    {{student.name}}
                </td>
                <td> <a href="{%url 'core:detailview' student.id%}" class="btn btn-primary">View Detail</a></td>
                
            </tr>
          {%endfor%}

        </tbody>
      </table>
      <!-- {{page}} -->
      <div class="container mt-2">
        <div class="row ">
            <div class="col-md-4 offset-lg-5">
                {%if students.has_other_pages%}
                <div>
                    <ul class="pagination pagination-lg container ">
                        {% if students.has_previous %}
                        <li class="page-item ">
                            <a class="page-link"
                                href="{%my_url students.previous_page_number 'page' request.GET.urlencode %}" tabindex="-1"
                                style="color: black;">Previous</a>
                        </li>
                        {%endif%}
                        {%for i in students.paginator.page_range%}
                        <!-- {{i}} -->
                        <li class="page-item  "><a class="page-link {%if i == page %} x {%endif%}" href="{%my_url i 'page' request.GET.urlencode %}"
                                style="color:rgb(56, 54, 51)">{{i}} </a></li>
      
                        {%endfor%}
                        {% if students.has_next %}
                        <li class="page-item ">
                            <a class="page-link" href="{%my_url students.next_page_number 'page' request.GET.urlencode %}"
                                tabindex="-1" style="color: black;">Next</a>
                        </li>
                        {%endif%}
                    </ul>
                </div>
                {%endif%}
            </div>
        </div>
        </div>
      
      {%else%}
      <div class="alert alert-dark" role="alert">
        No records available
      </div>
      {%endif%}
  </div>
<script>
   $("#livesearch").keyup(function(){
      var livesearch = $(this).val();
      console.log(livesearch)
      if (livesearch != " "){
        $.ajax(
          {
            type:'POST',
            url:"/searchdata/",
            data:{ 
              'livesearch':livesearch,
              'csrfmiddlewaretoken':'{{ csrf_token }}'
            },
            success:function(res){
              // console.log(data)
              $("#tbody").html(res.data)
            }
          }
        );
      }

   })
</script>
<!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script> -->
{%endblock content%}

core/templates/core/studentDetail.html
{%extends 'base.html'%}
{%block content%}
<div class="container">
    <div class="row  justify-content-center mt-2">
      <img src="{{collage.image.url}}" style = " width: 100px;"  alt="">
    </div>
    <p class="mt-2 text-center color-red">{{collage.name}}</p>
    <hr>  
    <div class="row justify-content-center my-3 ">
        
        <div class="col-sm-5 border p-5 shadow  rounded">
            {% if messages %}
                {% for msg in messages %}
                <div class="alert alert-warning alert-dismissible my-3  " role="alert">
                    <button type="button" class="close w-25" data-dismiss="alert" aria-label="Close">x</button>
                    

                    {{msg.message}}
                </div>
                {% endfor %}
        {% endif %}
        <h1>Register</h1>
        <hr>
             
            <form method = "post" novalidate>
                {%csrf_token%}
                {{form.as_p}}
                <input type="submit" class="btn btn-primary">
                
              </form>
        </div>
    </div>
</div>


{%endblock content%}

core/templates/core/viewStudents.html
{%extends 'base.html'%}

{%block content%}
{%load myapp_extras%}
<style>
  .x{
      background-color: rgb(242, 236, 236);
      
  }
</style>

<div class="container my-5">
  <form action="" class="mb-2 ml-auto">
    <div class="formgroup">

      <input type="text" class="form-control" placeholder = "search here" name = "livesearch" id = "livesearch">
    </div>
  </form>
  <!-- {{status}} -->
    <ul class="nav nav-pills nav-fill border mb-3">

        <li class="nav-item border-right">
          <a class="nav-link {%if status == 0%} active {%endif%}" href="/viewstudents/"  >All</a>
        </li>
        <li class="nav-item border-right">
          <a class="nav-link {%if status == 1%} active {%endif%}" href="?status=verified" >Verified</a>
        </li>
        <li class="nav-item border-right">
          <a class="nav-link {%if status == 2 %} active {%endif%}" href="?status=Not_verified" >Not Verified</a>
        </li>
      </ul>
      {%if students%}
    <table class="table border-bottom ">  
        <thead class="">
          <tr>
          
            <th>Students</th>
            <th></th>
          </tr>
        </thead>
        <tbody id = "tbody">
         {%for student in students%}
            <tr>
              
                <td>
                    {{student.name}}
                </td>
                <td> <a href="{%url 'core:detailview' student.id%}" class="btn btn-primary">View Detail</a></td>
                
            </tr>
          {%endfor%}

        </tbody>
      </table>
      <!-- {{page}} -->
      <div class="container mt-2">
        <div class="row ">
            <div class="col-md-4 offset-lg-5">
                {%if students.has_other_pages%}
                <div>
                    <ul class="pagination pagination-lg container ">
                        {% if students.has_previous %}
                        <li class="page-item ">
                            <a class="page-link"
                                href="{%my_url students.previous_page_number 'page' request.GET.urlencode %}" tabindex="-1"
                                style="color: black;">Previous</a>
                        </li>
                        {%endif%}
                        {%for i in students.paginator.page_range%}
                        <!-- {{i}} -->
                        <li class="page-item  "><a class="page-link {%if i == page %} x {%endif%}" href="{%my_url i 'page' request.GET.urlencode %}"
                                style="color:rgb(56, 54, 51)">{{i}} </a></li>
      
                        {%endfor%}
                        {% if students.has_next %}
                        <li class="page-item ">
                            <a class="page-link" href="{%my_url students.next_page_number 'page' request.GET.urlencode %}"
                                tabindex="-1" style="color: black;">Next</a>
                        </li>
                        {%endif%}
                    </ul>
                </div>
                {%endif%}
            </div>
        </div>
        </div>
      
      {%else%}
      <div class="alert alert-dark" role="alert">
        No records available
      </div>
      {%endif%}
  </div>
<script>
   $("#livesearch").keyup(function(){
      var livesearch = $(this).val();
      console.log(livesearch)
      if (livesearch != " "){
        $.ajax(
          {
            type:'POST',
            url:"/searchdata/",
            data:{ 
              'livesearch':livesearch,
              'csrfmiddlewaretoken':'{{ csrf_token }}'
            },
            success:function(res){
              // console.log(data)
              $("#tbody").html(res.data)
            }
          }
        );
      }

   })
</script>
<!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script> -->
{%endblock content%}