core/urls.py
app_name = "core"
from django.urls import path
from . import views

urlpatterns = [
    path("",views.index,name = "home"),
    path("add",views.add,name = "addcollage"),
    path("forms/<slug>",views.forms,name = "forms"),
    path("register/",views.register,name = "register"),
    path("login/",views.user_login,name = "login"),
    path('logout/',views.user_logout,name = 'logout'),
    path('viewstudents/',views.viewStudents,name = 'viewStudents'),
    path('detailview/<int:pk>',views.detailview,name = 'detailview'),
    path('delete/<int:pk>',views.deletecollage,name = 'delete'),
    path('searchdata/',views.searchdata,name = 'searchdata'),
    path('searchcollage/',views.searchcollage,name = 'searchcollage'),
    path('students/colllage/<slug>',views.student,name = "student"),
    path('first-time-login/changepassword',views.change,name = "change")
    ,path('changepassword',views.changepassword,name = "changepassword"),
    path('updateuser/<pk>',views.updateuser,name = "updateuser"),
    path('deleteuser/<pk>',views.deleteuser,name = "deleteuser"),
    path('viewuser',views.viewuser,name = "viewuser"),
    
    
]

qr/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('core.urls')),
    
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <title>Sikshyashala</title>
    <link rel="icon" type="image/x-icon" href="{% static 'img/sikshyashala.png'%}">
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>

  </head>
  <body>
  

    <!-- As a link -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container">
      <a class="navbar-brand" href="{%url 'core:home'%}"><img src="{% static 'img/sikshyashala.png'%}" style = "width: 200px  ;"alt=""></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ml-auto">
          
          <li class="nav-item">
            
          </li>
        
          {%if request.user.is_authenticated %}
              
          <li class="nav-item active">
            <a class="nav-link" href="{%url 'core:home'%}">Home <span class="sr-only">(current)</span></a>
          </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Welcome, {{request.user}}
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  {%if request.user.is_superuser%}
                  <a class="dropdown-item" href="{%url 'core:addcollage' %}">Add collage</a>
                  <a class="dropdown-item" href="{%url 'core:register'%}">Create User Account</a>
                  <a class="dropdown-item" href="{%url 'core:viewuser'%}">View Users</a>
                  {%endif%}
                  {%if request.user.is_staff == False%}
                  <a class="dropdown-item" href="{%url 'core:viewStudents'%}">View Students</a>
                  {%endif%}
                  <a class="dropdown-item" href="{%url 'core:changepassword'%}">Change Password</a>
                  <a class="dropdown-item" href="{%url 'core:logout'%}">logout</a>
                 

                </div>
              </li>
              
                
              {%endif%}
             
        </ul>
      </div>
    </div>
    </nav>

        {%block content%}
        {%endblock content%}
        
   
          

        <!-- As a heading -->
      <script src="https://unpkg.com/htmx.org@1.1.0"></script>
      <script>
        document.body.addEventListener('htmx:configRequest', (event) => {
          event.detail.headers['X-CSRFToken'] = '{{ csrf_token }}';
        })
      </script>
    <!-- <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script> -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>

    
  </body>
</html>